name: e-charge
favicon: null
layout_spectrum: 1
typography_spectrum: 0.74331
title: News about changing combustion to charging
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fefefe'
    - '#7f7f7f'
    - '#501d08'
    - '#d98d3f'
  brandStrength: 0.1875
  lightness: 0.803438174771145
  saturation: 0.3125
  rhythmicContrast: 0
purpose: []
