name: e-charge
favicon: null
layout_spectrum: 0.4229
typography_spectrum: 0.12882
title: News about changing from combustion to charging
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#4faad9'
    - '#b6cad1'
    - '#335177'
    - '#ea7403'
  brandStrength: 0.875
  lightness: 0.803438174771145
  saturation: 0.625
  rhythmicContrast: 0
purpose: []
