name: e-charge
favicon: null
layout_spectrum: 1
typography_spectrum: 0.74331
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#080808'
    - '#353535'
    - '#969696'
    - '#c5c5c5'
    - '#fcfcfc'
  brandStrength: 0.1875
  lightness: 0.803438174771145
  saturation: 0.6875
  rhythmicContrast: 0.610759362578392
purpose: []
